services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/base:bookworm
    command: sleep infinity
    volumes:
      - ..:/workspace:cached

  mailpit:
    image: axllent/mailpit:latest
    ports:
      - 1025:1025
      - 8025:8025

  plantuml:
    image: plantuml/plantuml-server:latest
    ports:
      - 9090:8080
